name: visitor_app
description: "اپلیکیشن ویزیتور برای مدیریت سفارشات، مسیر‌یابی و نوتیفیکیشن‌ها"
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0

  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  flutter_local_notifications: ^19.4.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3   # نسخه پایین‌تر برای سازگاری بهتر
  provider: ^6.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
