name: visitor_app
description: "اپلیکیشن ویزیتور پایدار"
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2

  firebase_core: 1.24.0
  cloud_firestore: 3.4.7
  firebase_auth: 3.11.2
  firebase_storage: 10.3.10
  firebase_messaging: 11.4.4

  cached_network_image: 3.2.3
  connectivity_plus: 3.0.3
  flutter_local_notifications: 9.6.0
  geolocator: 8.2.1
  google_maps_flutter: 2.2.0
  provider: 6.0.5
  sqflite: 2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
